apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deployment
  labels:
    app: contact
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
      - name: contact
        image: 679818959710.dkr.ecr.us-east-1.amazonaws.com/contact-poc:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: contact-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: contact-secret
              key: db-password
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: contact-config
              key: app-port
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: contact-config
              key: node-env
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: contact-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: contact-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: contact-config
              key: db-name
        - name: DB_LOGGING
          valueFrom:
            configMapKeyRef:
              name: contact-config
              key: db-logging
        - name: DB_SYNC
          valueFrom:
            configMapKeyRef:
              name: contact-config
              key: db-sync
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: contact-config
              key: db-schema
---
apiVersion: v1
kind: Service
metadata:
  name: contact-service
spec:
  type: NodePort
  selector:
    app: contact
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30201
